# EMBEDDED SERVER CONFIGURATION
server:
    port: ${port:8090}

spring:
    aop:
        proxyTargetClass: true
# ZULL
zuul:
  routes:
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user
    auth-service:
      sensitiveHeaders:
      path: /oauth/**
      stripPrefix: false
    # ai-service should be moved to path other than /
    api-service:
      sensitiveHeaders:
      path: /api/**
      stripPrefix: true
  add-proxy-headers: true
#SECURITY
security:
  user:
    password: password
  oauth2:
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: http://localhost:9999/uaa/user

# LOGGING
#logging.level.org.springframework.security: DEBUG

---

#spring:
#  profiles: docker

# EUREKA
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://discovery-service:8081/eureka/

---

#spring:
#  profiles: standalone

# EUREKA
#eureka:
#  instance:
#    hostname: localhost
#    port: 8081
#  client:
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/