# EMBEDDED SERVER CONFIGURATION
server:
    port: ${port:8090}

spring:
    aop:
        proxyTargetClass: true

# ZULL


zuul:
  routes:
    user:
      path: /user/**
      url: http://localhost:9999/user
    ksb-auth:
      sensitiveHeaders:
      path: /oauth/**
      stripPrefix: false
    # ai-service should be moved to path other than /
    ksb-api-products:
      sensitiveHeaders:
      path: /api/**
      stripPrefix: true
  add-proxy-headers: true
#SECURITY

security:
  basic:
    enabled: false
  oauth2:
    sso:
      loginPath: /login
    resource:
      jwt:
        keyValue: |
              -----BEGIN PUBLIC KEY-----
                MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq/IMQ+H79ccMt77OS1zGgxV9uHL5CAI4OQ8OTa3VXMwXDVIn3zZb8Knwgd9QxQQWK+9DnMp0y+jPGVIgiiA8FU5nlGrZ2yfZqBGEgR0L+EUY2IGC1ew1u50p+lqz79D5+G7B5RkhC9Tiu/d2iOsnULuIlasfLO520hNR6Zib1Ezwf5Xnj/GGkpKJMmmhOEQG35DkZwGA4/AvWX/giTQ157HpQEthhe8YLJIu1RyoIFNjQbiJWnDkP7mFqctmWucyaUfS71a15E5DXDDytQX5zPh78NYlGIMvvtT6IgY4560UGAtpOSg/wiYFakQOan5PU9Fcnx1ykS54wUQoQFBQ7QIDAQAB
              -----END PUBLIC KEY-----
      id: openid
      serviceId: ${PREFIX:}resource


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://ksb-discovery:8761/eureka/}

#security:
#  oauth2:
#    client:
#      accessTokenUri: http://localhost:9999/oauth/token
#      userAuthorizationUri: http://localhost:9999/oauth/authorize
#      clientId: acme
#      clientSecret: acmesecret
#    resource:
#      userInfoUri: http://localhost:9999/user

# LOGGING
#logging.level.org.springframework.security: DEBUG

---

#spring:
#  profiles: docker

# EUREKA
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://discovery-service:8081/eureka/

---

#spring:
#  profiles: standalone

# EUREKA
#eureka:
#  instance:
#    hostname: localhost
#    port: 8081
#  client:
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/