server:
  port: 7070

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user

spring:
  jpa:
   hibernate:
    ddl-auto: create-drop
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springbootdb
    username: postgres
    password: user